<?php

// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use common\models\Email;
use yii\helpers\Html;
use common\helpers\OeHelpers;
use common\models\Book;
use common\models\BookDeals;


class CommunicationController extends Controller {

    public function actionSendEmail($id) {

        Yii::$app->response->format = \Yii::$app->response->format = 'json';
        $data = [];
        if (Yii::$app->request->isAjax) {

            $book = Book::find()->andWhere(['id' => $id])->one();

            $queryDeals = BookDeals::find()
                    ->where(['book_id' => $id]);
            $modelDeals = new \yii\data\ActiveDataProvider([
                'query' => $queryDeals,
                'sort' =>false
            ]);
            
            $rating = !empty($book->rating) ? str_repeat('⋆',$book->rating) : '';
            
            $model = new Email();
            $model->name = 'Event Planner';
            $model->email = 'eduardo@open-ecommerce.org';
            $model->subject = 'UK Tango Report: ' . $book->title . ' '. $rating;
            $model->body = 'to be replaced';
            
            $userMail = Yii::$app->user->identity->email;
            
            if ($model->emailContact($userMail,$book,$modelDeals)) {
                Yii::$app->getSession()->setFlash('info', [
                    'type' => 'success',
                    'icon' => 'fa fa-envelope',
                    'title' => \Yii::t('app', Html::encode('Sending Email')),
                    'message' => \Yii::t('app', Html::encode("Sent to: " . $userMail)),
                ]);
                $data = ['sucess' => true, 'class' => 'sent'];
            } else {
                Yii::$app->getSession()->setFlash('alert', [
                    'type' => 'success',
                    'icon' => 'fa fa-envelope',
                    'title' => \Yii::t('app', Html::encode('Sending Email')),
                    'message' => \Yii::t('app', Html::encode("Some kind of problem sending the mail")),
                ]);
                $data = ['sucess' => true, 'class' => 'not-sent'];
            }
            return $data;
        }
    }

}
