<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add emails' => '',
    'Administrator' => '',
    'Answer' => '',
    'Are you sure you want to close the ticket?' => '',
    'Are you sure you want to delete this Right?' => '',
    'Are you sure you want to delete this User?' => '',
    'Are you sure you want to delete this book?' => '',
    'Are you sure you want to delete this contact?' => '',
    'Are you sure you want to delete this group?' => '',
    'Client' => '',
    'Close' => '',
    'Date' => '',
    'Date Updated' => '',
    'Delete' => '',
    'Delete this book.' => '',
    'Delete this contact.' => '',
    'Delete this group.' => '',
    'Delete this right.' => '',
    'Delete this user.' => '',
    'Departament' => '',
    'Developer' => '',
    'Do you really want to delete?' => '',
    'Document name' => '',
    'Edit' => '',
    'Edit Book' => '',
    'File Name' => '',
    'Frequency' => '',
    'Go Back' => '',
    'ID' => '',
    'Id Body' => '',
    'In progress' => '',
    'Info' => '',
    'Link' => '',
    'Message' => '',
    'Name' => '',
    'Name User' => '',
    'New Ticket' => '',
    'No comments found.' => '',
    'Official submission' => '',
    'Open' => '',
    'Please write about the book\'s origin' => '',
    'Please write about the rights...' => '',
    'Please write something about your self' => '',
    'Please write the mini abstract of the report...' => '',
    'Please write the rational for the recommendation' => '',
    'Reply' => '',
    'Send Ticket' => '',
    'Send ticket' => '',
    'Status' => '',
    'Text' => '',
    'This email is generated automatically by the system notification service. You do not need to respond to it.' => '',
    'User ID' => '',
    'Username' => '',
    'View' => '',
    'View book' => '',
    'Waiting' => '',
    'You are not allowed to {0} record #{1}' => '',
    '{n} characters remaining' => '',
    'Тopic' => '',
];
