<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<a href="{link}">Forgot details?</a>' => '',
    'About us' => '',
    'Account Settings' => '',
    'Activation email' => '',
    'Administration' => '',
    'Articles' => '',
    'Attachments' => '',
    'Body' => '',
    'Bookmarks' => '',
    'Books' => '',
    'Change photo peeeeeeeeeese' => '',
    'Check your email for further instructions.' => '',
    'Confirm Password' => '',
    'Dashboard' => '',
    'E-mail' => '',
    'Email' => '',
    'Email *' => '',
    'Error while oauth process.' => '',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => '',
    'Incorrect username or password.' => '',
    'Log in with' => '',
    'Login' => '',
    'Logout' => '',
    'My Profile' => '',
    'Name' => '',
    'Need an account? Sign up.' => '',
    'New password was saved.' => '',
    'Page not found' => '',
    'Password' => '',
    'Password *' => '',
    'Password reset for {name}' => '',
    'Profile settings' => '',
    'Remember Me' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Save & View' => '',
    'Send me email with new password link' => '',
    'Shouts and Murmurs' => '',
    'Sign in' => '',
    'Sign in to your dashboard' => '',
    'Sign me in' => '',
    'Sign up with' => '',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Subject' => '',
    'Submit' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'There was an error sending email.' => '',
    'This email address has already been taken.' => '',
    'This email has already been taken.' => '',
    'This username has already been taken.' => '',
    'Update' => '',
    'User Settings' => '',
    'Username' => '',
    'Username *' => '',
    'Username or email' => '',
    'Verification Code' => '',
    'We already have a user with email {email}' => '',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => '',
    'Your account has been successfully activated.' => '',
    'Your account has been successfully created. Check your email for further instructions.' => '',
    'Your account has been successfully saved' => '',
    'Your activation link: {url}' => '',
    '{app-name} | Your login information' => '',
];
