<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "user_bookmark".
 *
 * @property integer $id
 * @property integer $bookmark_id
 * @property string $url
 * @property string $type
 * @property string $selectedTime
 * @property string $aliasModel
 */
abstract class Bookmark extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_bookmark';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'bookmark_id', 'url', 'type', 'author', 'title'], 'required'],
            [['selectedTime'], 'safe'],
            [['url'], 'string', 'max' => 50],
            [['type', 'user_id', 'bookmark_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'url' => Yii::t('models', 'Url'),
            'type' => Yii::t('models', 'Bookmark Type'),
            'title' => Yii::t('models', 'Title'),
            'author' => Yii::t('models', 'Author'),
            'selectedTime' => Yii::t('models', 'Selected Time'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\UserBookmarkQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BookmarkQuery(get_called_class());
    }


}
