<?php

// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use common\models\Country;

/**
 * This is the base-model class for table "company".
 *
 * @property integer $id
 * @property integer $country_id
 * @property string $name
 * @property string $notes
 * @property string $allowed_categories
 * @property string $aliasModel
 */
abstract class Company extends \yii\db\ActiveRecord {

    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'company';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['name', 'country_id'], 'required'],
            [['name'], 'unique'],
            [['notes'], 'string'],
            [['status'], 'integer'],
            [['name', 'allowed_categories'], 'string', 'max' => 1000],
            [['country_id'], 'exist', 'targetClass' => Country::className(), 'targetAttribute' => 'id'],            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('models', 'ID'),
            'country_id' => Yii::t('common', 'Country of trading'),            
            'name' => Yii::t('models', 'Name'),
            'notes' => Yii::t('models', 'Notes'),
            'allowed_categories' => Yii::t('models', 'Allowed Categories'),
            'status' => Yii::t('common', 'Active Company'),            
        ];
    }

    /**
     * @inheritdoc
     * @return \common\models\CompanyQuery the active query used by this AR class.
     */
    public static function find() {
        return new \common\models\query\CompanyQuery(get_called_class());
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountry() {
        return $this->hasOne(Country::className(), ['id' => 'country_id']);
    }    
    
    
}
