<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use common\models\ContactTypeQuery;

/**
 * This is the base-model class for table "contact_type".
 *
 * @property integer $id
 * @property string $type
 *
 * @property \app\models\Contact[] $contacts
 * @property string $aliasModel
 */
abstract class ContactType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contact_type';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'type' => Yii::t('backend', 'Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContacts()
    {
        return $this->hasMany(Contact::className(), ['contact_type_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\ContactTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ContactTypeQuery(get_called_class());
    }


}
