<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "country".
 *
 * @property integer $id
 * @property string $country_code
 * @property string $country_name
 *
 * @property \common\models\BookDeals[] $bookRights
 * @property string $aliasModel
 */
abstract class Country extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'country';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['country_code'], 'string', 'max' => 2],
            [['country_name'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'country_code' => Yii::t('models', 'Country Code'),
            'country_name' => Yii::t('models', 'Country Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookDeals()
    {
        return $this->hasMany(\common\models\BookDeals::className(), ['country_id' => 'id']);
    }

    
    /**
     * @inheritdoc
     * @return \common\models\CountryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CountryQuery(get_called_class());
    }


}
