<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ticket_type".
 *
 * @property integer $id
 * @property string $ticket_name
 *
 * @property \common\models\TicketDates[] $ticketDates
 * @property string $aliasModel
 */
abstract class TicketType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ticket_type';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ticket_name'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ticket_name' => Yii::t('models', 'Ticket Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTicketDates()
    {
        return $this->hasMany(\common\models\TicketDates::className(), ['ticket_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\TicketTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\TicketTypeQuery(get_called_class());
    }


}
