<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;
use trntv\filekit\behaviors\UploadBehavior;

use Yii;

/**
 * This is the base-model class for table "ticket".
 *
 * @property integer $id
 * @property integer $barcode
 * @property integer $transaction_id
 * @property integer $attendee_id
 * @property integer $registration_id
 * @property string $registration_time
 * @property string $registration_code
 * @property string $registration_status
 * @property string $transaction_status
 * @property double $transaction_amount
 * @property double $amount_paid
 * @property string $payment_date
 * @property string $payment_method
 * @property string $geteway_transaction
 * @property string $ticket_name
 * @property string $ticket_date
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $address_1
 * @property string $address_2
 * @property string $city
 * @property string $state
 * @property string $country
 * @property string $postal_code
 * @property string $phone
 * @property string $notes
 * @property string $dance_partner
 * @property string $dance_partner_nationality
 * @property string $aliasModel
 */
abstract class Ticket extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ticket';
    }

    public $thumbnail;        
    public $barcodeSearch;        
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => UploadBehavior::className(),
                'attribute' => 'thumbnail',
                'pathAttribute' => 'thumbnail_path',
                'baseUrlAttribute' => 'thumbnail_base_url'
            ]
        ];
    }    
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'transaction_id', 'attendee_id', 'registration_id', 'ticket_type_id'], 'integer'],
            [['thumbnail','registration_time', 'payment_date', 'ticket_date'], 'safe'],
            [['transaction_amount', 'amount_paid'], 'number'],
            [['notes'], 'string'],
            [['first_name', 'last_name', 'ticket_type_id'], 'required'],
            [['registration_code', 'registration_status', 'transaction_status', 'payment_method', 'geteway_transaction', 'address_1', 'address_2', 'city', 'state', 'country', 'postal_code', 'phone', 'dance_partner', 'dance_partner_nationality'], 'string', 'max' => 50],
            [['barcodeSearch','barcode', 'ticket_name', 'first_name', 'last_name', 'email'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'barcode' => Yii::t('models', 'Barcode'),
            'transaction_id' => Yii::t('models', 'Transaction ID'),
            'attendee_id' => Yii::t('models', 'Attendee ID'),
            'registration_id' => Yii::t('models', 'Registration ID'),
            'registration_time' => Yii::t('models', 'Registration Time'),
            'registration_code' => Yii::t('models', 'Registration Code'),
            'registration_status' => Yii::t('models', 'Registration Status'),
            'transaction_status' => Yii::t('models', 'Transaction Status'),
            'transaction_amount' => Yii::t('models', 'Transaction Amount'),
            'amount_paid' => Yii::t('models', 'Amount Paid'),
            'payment_date' => Yii::t('models', 'Payment Date'),
            'payment_method' => Yii::t('models', 'Payment Method'),
            'geteway_transaction' => Yii::t('models', 'Geteway Transaction'),
            'ticket_type_id' => Yii::t('models', 'Ticket Type'),
            'ticket_name' => Yii::t('models', 'WP Ticket Name'),
            'ticket_date' => Yii::t('models', 'Ticket Date'),
            'first_name' => Yii::t('models', 'First Name'),
            'last_name' => Yii::t('models', 'Last Name'),
            'email' => Yii::t('models', 'Email'),
            'address_1' => Yii::t('models', 'Address 1'),
            'address_2' => Yii::t('models', 'Address 2'),
            'city' => Yii::t('models', 'City'),
            'state' => Yii::t('models', 'State'),
            'country' => Yii::t('models', 'Country'),
            'postal_code' => Yii::t('models', 'Postal Code'),
            'phone' => Yii::t('models', 'Phone'),
            'notes' => Yii::t('models', 'Notes'),
            'dance_partner' => Yii::t('models', 'Dance Partner'),
            'dance_partner_nationality' => Yii::t('models', 'Dance Partner Nationality'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\Ticket the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\TicketQuery(get_called_class());
    }


}
