<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ticket_attendance".
 *
 * @property integer $id
 * @property integer $ticket_id
 * @property integer $venue_id
 * @property string $attendance
 *
 * @property \common\models\Ticket $ticket
 * @property string $aliasModel
 */
abstract class TicketAttendance extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ticket_attendance';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ticket_id', 'attendance'], 'required'],
            [['ticket_id', 'venue_id'], 'integer'],
            [['attendance'], 'safe'],
            [['ticket_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Ticket::className(), 'targetAttribute' => ['ticket_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ticket_id' => Yii::t('models', 'Ticket ID'),
            'attendance' => Yii::t('models', 'Attendance'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTicket()
    {
        return $this->hasOne(\common\models\Ticket::className(), ['id' => 'ticket_id']);
    }

    public function getVenue()
    {
        return $this->hasOne(\common\models\Venue::className(), ['id' => 'venue_id']);
    }

    
    /**
     * @inheritdoc
     * @return \common\models\TicketAttendanceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\TicketAttendanceQuery(get_called_class());
    }


}
