<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ticket_dates".
 *
 * @property integer $id
 * @property integer $ticket_id
 * @property string $ticket_date
 *
 * @property \common\models\TicketType $ticket
 * @property string $aliasModel
 */
abstract class TicketDates extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ticket_dates';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ticket_id'], 'integer'],
            [['ticket_date'], 'safe'],
            [['ticket_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\TicketType::className(), 'targetAttribute' => ['ticket_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'ticket_id' => Yii::t('models', 'Ticket ID'),
            'ticket_date' => Yii::t('models', 'Ticket Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTicket()
    {
        return $this->hasOne(\common\models\TicketType::className(), ['id' => 'ticket_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\TicketDatesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\TicketDatesQuery(get_called_class());
    }


}
