<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "qry_total_tickets".
 *
 * @property integer $id
 * @property string $ticket_name
 * @property integer $total
 * @property string $role
 * @property string $aliasModel
 */
abstract class TotalCheckin extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'qry_checkin';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 200],
            [['role'], 'string', 'max' => 50],
            [['attandance'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
//            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Ticket Name'),
            'attendance' => Yii::t('models', 'Time Checkin'),
            'role' => Yii::t('models', 'Role'),
        ];
    }


//
//    /**
//     * @inheritdoc
//     * @return \app\modules\crud\models\query\QryTotalTicketQuery the active query used by this AR class.
//     */
//    public static function find()
//    {
//        return new \common\models\query\CheckinQuery(get_called_class());
//
//    }
//
//    public static function findCheckinToday()
//    {
//        return new \common\models\query\CheckinQuery(get_called_class());
//
//    }
}
