<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "qry_total_tickets".
 *
 * @property integer $id
 * @property string $ticket_name
 * @property integer $total
 * @property string $role
 * @property string $aliasModel
 */
abstract class TotalTickets extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'qry_total_tickets';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['total'], 'integer'],
            [['ticket_name'], 'string', 'max' => 200],
            [['role'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
//            'id' => Yii::t('models', 'ID'),
            'ticket_name' => Yii::t('models', 'Ticket Name'),
            'total' => Yii::t('models', 'Total'),
            'role' => Yii::t('models', 'Role'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\modules\crud\models\query\QryTotalTicketQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\TicketQuery(get_called_class());
    }


}
