<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "venue".
 *
 * @property integer $id
 * @property string $name
 * @property integer $country_id
 * @property string $address_1
 * @property string $address_2
 * @property string $address_3
 * @property string $city
 * @property string $postal_code
 *
 * @property \common\models\Country $country
 * @property string $aliasModel
 */
abstract class Venue extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'venue';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['country_id'], 'integer'],
            [['name', 'address_1', 'address_2', 'address_3', 'city', 'postal_code'], 'string', 'max' => 100],
            [['country_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Country::className(), 'targetAttribute' => ['country_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Venue'),
            'country_id' => Yii::t('models', 'Country ID'),
            'address_1' => Yii::t('models', 'Address 1'),
            'address_2' => Yii::t('models', 'Address 2'),
            'address_3' => Yii::t('models', 'Address 3'),
            'city' => Yii::t('models', 'City'),
            'postal_code' => Yii::t('models', 'Postal Code'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountry()
    {
        return $this->hasOne(\common\models\Country::className(), ['id' => 'country_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\VenueQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\VenueQuery(get_called_class());
    }


}
